Summary tests
metrumresearchgroup/babylontest pull request #15
Opened 2020-08-21 13:54 UTC by seth127

Adding some basic tests of `bbi nonmem summary` using golden files

2020-08-21 16:16 UTC, seth127 commented
One question here is: when I run these locally I have to set the `ROOT_EXECUTION_DIR` environment var like so
```
ROOT_EXECUTION_DIR=. go test -v -run TestSummary
```
because I'm _not_ using the `Scenarios` construct for two reasons:
1. I don't need it because I'm not writing anything to disk
2. It breaks my ability to have the `-update_summary` flag for updating the golden files.

@shairozan we should talk on this and make sure I'm cool in drone, or if maybe there's another way to accomplish the update thing that's a bit slicker.

2020-08-26 14:47 UTC, shairozan commented on bbi_summary_test.go
> +		if (tc.bbiFlag != "") {
As a note, go does not require the parentheses

```go
 if tc.bbiFlag != "" {
}
```

is valid and more idiomatic

2020-08-26 14:47 UTC, shairozan commented on bbi_summary_test.go
> +		if *update_summary {
I do very much like the fact you built in a way to update the golden file without having to manually copy files around

2020-08-26 14:51 UTC, shairozan requested changes
We'll want a few more tests than just the happy path for summary. What happens if:

1. The model / directory targeted doesn't exist? 
2. The model / directory exists but the files necessary to run summary did not (IE failed grid submission)

What we want to do is make sure that we _understand_ babylon's behavior. If it's going to panic in these scenarios, let's update Babylon to accommodate these without panics and verify that behavior in the tests.

Overall good reconciliation of the complicated test structures we have for babylon and navigating that to create useful tests for Babylon

2020-08-26 15:17 UTC, merged